/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/ai-consent": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Consent */
        get: operations["get_consent_api_v1_ai_consent_get"];
        /** Grant Consent */
        put: operations["grant_consent_api_v1_ai_consent_put"];
        post?: never;
        /** Revoke Consent */
        delete: operations["revoke_consent_api_v1_ai_consent_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Health
         * @description Return application health summary with Cache-Control: no-store.
         */
        get: operations["get_health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/operations/{operationId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Operation */
        get: operations["get_operation_api_v1_operations__operation_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Sources */
        get: operations["get_sources_api_v1_sources_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sync-runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Sync Run */
        post: operations["create_sync_run_api_v1_sync_runs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sync-runs/{syncRunId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Sync Run */
        get: operations["get_sync_run_api_v1_sync_runs__syncRunId__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/word-forms": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Word Forms */
        get: operations["list_word_forms_api_v1_word_forms_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/word-forms/{wordFormId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Word Form */
        get: operations["get_word_form_api_v1_word_forms__wordFormId__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bootstrap/exchange": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Exchange Bootstrap */
        post: operations["exchange_bootstrap_bootstrap_exchange_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AiConsentMutationResult */
        AiConsentMutationResult: {
            /** Appliedrevision */
            appliedRevision: number;
            /** Operationid */
            operationId: string;
        };
        /** AiConsentView */
        AiConsentView: {
            /** Acceptedpolicydigest */
            acceptedPolicyDigest: string | null;
            /** Acceptedpolicyversion */
            acceptedPolicyVersion: string | null;
            /** Canrequestai */
            canRequestAi: boolean;
            /** Lastchoiceat */
            lastChoiceAt: string | null;
            policy: components["schemas"]["AiDisclosurePolicy"] | null;
            /** Revision */
            revision: number;
            /**
             * State
             * @enum {string}
             */
            state: "NOT_GRANTED" | "GRANTED" | "REVOKED" | "STALE";
        };
        /** AiDisclosurePolicy */
        AiDisclosurePolicy: {
            /** Blockedreasons */
            blockedReasons: ("MODEL_POLICY" | "QUOTA_BILLING" | "PROXY_DATA_POLICY" | "CLOUD_DATA_POLICY")[];
            /** Costquotastatement */
            costQuotaStatement: string;
            /** Datacategories */
            dataCategories: ("TERM" | "WORD_FORMS" | "WRITING_ANSWER")[];
            /** Digest */
            digest: string;
            /** Disclosuretext */
            disclosureText: string;
            /** Dispatchrules */
            dispatchRules: components["schemas"]["AiDispatchRule"][];
            /** Recipients */
            recipients: string[];
            /** Regionstatement */
            regionStatement: string;
            /** Retentionstatement */
            retentionStatement: string;
            /**
             * Reviewstatus
             * @enum {string}
             */
            reviewStatus: "BLOCKED" | "READY";
            /** Scopes */
            scopes: ("LOOKUP" | "QUIZ_GENERATION" | "WRITING_FEEDBACK")[];
            /** Version */
            version: string;
            /** Withdrawalstatement */
            withdrawalStatement: string;
        };
        /** AiDispatchRule */
        AiDispatchRule: {
            /**
             * Billingmode
             * @constant
             */
            billingMode: "configured-account";
            /**
             * Modelid
             * @constant
             */
            modelId: "gemini-3.8-flash-high";
            /**
             * Providerlabel
             * @constant
             */
            providerLabel: "Antigravity/Google";
            /**
             * Route
             * @constant
             */
            route: "primary";
            /**
             * Scope
             * @enum {string}
             */
            scope: "LOOKUP" | "QUIZ_GENERATION" | "WRITING_FEEDBACK";
        };
        /** BootstrapExchange */
        BootstrapExchange: {
            /** Token */
            token: string;
        };
        /**
         * BridgeStatus
         * @description AI bridge adapter status.
         * @enum {string}
         */
        BridgeStatus: "NOT_CHECKED" | "OK" | "NOT_READY";
        /** CardView */
        CardView: {
            /** Dueat */
            dueAt: string | null;
            /** Id */
            id: string;
            /** State */
            state: string;
        };
        /** ConsentError */
        ConsentError: {
            /** Code */
            code: string;
            details?: components["schemas"]["ConsentRetryDetails"] | null;
            /** Message */
            message: string;
            /** Requestid */
            requestId: string;
        };
        /** ConsentErrorResponse */
        ConsentErrorResponse: {
            error: components["schemas"]["ConsentError"];
        };
        /** ConsentRetryDetails */
        ConsentRetryDetails: {
            /**
             * Kind
             * @constant
             */
            kind: "RETRY";
            /** Operationid */
            operationId: string;
        };
        /** CreateSyncRunRequest */
        CreateSyncRunRequest: {
            /**
             * Reason
             * @enum {string}
             */
            reason: "STARTUP" | "MANUAL" | "WATCHER";
        };
        ErrorDetails: {
            fields: {
                field: string;
                reason: string;
            }[];
            /** @enum {string} */
            kind: "FIELD_ERRORS";
        };
        ErrorResponse: {
            error: {
                code: string;
                details?: components["schemas"]["ErrorDetails"];
                message: string;
                requestId: string;
            };
        };
        /** ExampleView */
        ExampleView: {
            /** English */
            english: string;
            /**
             * Verificationstatus
             * @enum {string}
             */
            verificationStatus: "VERIFIED" | "UNVERIFIED" | "MISSING";
            /** Vietnamese */
            vietnamese: string;
        };
        /** GrantAiConsent */
        GrantAiConsent: {
            /** Policyversion */
            policyVersion: string;
        };
        /**
         * HealthStatus
         * @description Overall application health status.
         * @enum {string}
         */
        HealthStatus: "OK" | "DEGRADED" | "NOT_READY";
        /**
         * HealthSummary
         * @description Normative health schema matching docs/api-contract.md §183.
         */
        HealthSummary: {
            bridgeStatus: components["schemas"]["BridgeStatus"];
            /** Readiness */
            readiness: boolean;
            status: components["schemas"]["HealthStatus"];
            storageStatus: components["schemas"]["StorageStatus"];
            /** Version */
            version: string;
        };
        /** MeaningView */
        MeaningView: {
            /** Language */
            language: string;
            /** Text */
            text: string;
            /**
             * Verificationstatus
             * @enum {string}
             */
            verificationStatus: "VERIFIED" | "UNVERIFIED" | "MISSING";
        };
        /** Operation */
        Operation: {
            /** Createdat */
            createdAt: string;
            /** Errorcategory */
            errorCategory?: string | null;
            /** Kind */
            kind: string;
            /** Operationid */
            operationId: string;
            /** Resultref */
            resultRef?: string | null;
            /**
             * Status
             * @enum {string}
             */
            status: "PENDING" | "SUCCEEDED" | "FAILED" | "UNKNOWN";
            /** Updatedat */
            updatedAt: string;
        };
        /** PagePagination */
        PagePagination: {
            /** Hasmore */
            hasMore: boolean;
            /** Nextcursor */
            nextCursor?: string | null;
            /** Pagesize */
            pageSize: number;
        };
        /** PageSort */
        PageSort: {
            /** By */
            by: string;
            /**
             * Direction
             * @enum {string}
             */
            direction: "ASC" | "DESC";
        };
        /** PaginationView */
        PaginationView: {
            /** Hasmore */
            hasMore: boolean;
            /** Nextcursor */
            nextCursor: string | null;
            /** Pagesize */
            pageSize: number;
        };
        /** SortView */
        SortView: {
            /**
             * By
             * @enum {string}
             */
            by: "relevance" | "updatedAt" | "lemma";
            /**
             * Direction
             * @enum {string}
             */
            direction: "ASC" | "DESC";
        };
        /** SourceFilePage */
        SourceFilePage: {
            /** Data */
            data: components["schemas"]["SourceFileView"][];
            pagination: components["schemas"]["PagePagination"];
            sort: components["schemas"]["PageSort"];
        };
        /** SourceFileView */
        SourceFileView: {
            /** Errorcode */
            errorCode?: string | null;
            /** Etag */
            etag: string;
            /** Id */
            id: string;
            /** Lastparsedat */
            lastParsedAt?: string | null;
            /** Notedate */
            noteDate: string;
            /** Relativepath */
            relativePath: string;
            /** Revision */
            revision: number;
            /**
             * Status
             * @enum {string}
             */
            status: "VALID" | "INVALID" | "MISSING";
        };
        /** SourceReferenceView */
        SourceReferenceView: {
            /** Notedate */
            noteDate: string;
            /** Sourceid */
            sourceId: string;
            /**
             * Status
             * @enum {string}
             */
            status: "VALID" | "INVALID" | "MISSING";
        };
        /**
         * StorageStatus
         * @description Storage availability status.
         * @enum {string}
         */
        StorageStatus: "OK" | "NOT_READY";
        /** SyncRunConflictError */
        SyncRunConflictError: {
            /**
             * Code
             * @constant
             */
            code: "IDEMPOTENCY_IN_FLIGHT";
            details: components["schemas"]["SyncRunRetryDetails"];
            /** Message */
            message: string;
            /** Requestid */
            requestId: string;
        };
        /** SyncRunConflictErrorResponse */
        SyncRunConflictErrorResponse: {
            error: components["schemas"]["SyncRunConflictError"];
        };
        /** SyncRunRetryDetails */
        SyncRunRetryDetails: {
            /**
             * Kind
             * @constant
             */
            kind: "RETRY";
            /** Operationid */
            operationId: string;
        };
        /** SyncRunView */
        SyncRunView: {
            /** Finishedat */
            finishedAt?: string | null;
            /** Id */
            id: string;
            /** Operationid */
            operationId: string;
            /**
             * Reason
             * @enum {string}
             */
            reason: "STARTUP" | "MANUAL" | "WATCHER";
            /** Sourcerevision */
            sourceRevision?: number | null;
            /** Sourcesinvalid */
            sourcesInvalid: number;
            /** Sourcesscanned */
            sourcesScanned: number;
            /** Startedat */
            startedAt: string;
            /**
             * Status
             * @enum {string}
             */
            status: "QUEUED" | "RUNNING" | "COMPLETED" | "FAILED";
        };
        /** WordFormCollection */
        WordFormCollection: {
            /** Data */
            data: components["schemas"]["WordFormSummary"][];
            pagination: components["schemas"]["PaginationView"];
            sort: components["schemas"]["SortView"];
        };
        /** WordFormDetail */
        WordFormDetail: {
            /** Cambridgeurl */
            cambridgeUrl: string | null;
            card: components["schemas"]["CardView"] | null;
            /** Examples */
            examples: components["schemas"]["ExampleView"][];
            /** Familyid */
            familyId: string;
            /** Id */
            id: string;
            /** Ipaus */
            ipaUs: string | null;
            /** Lemma */
            lemma: string;
            /** Meaningsen */
            meaningsEn: components["schemas"]["MeaningView"][];
            /** Meaningsvi */
            meaningsVi: components["schemas"]["MeaningView"][];
            /** Partofspeech */
            partOfSpeech: string;
            /** Revision */
            revision: number;
            /** Sourcerefs */
            sourceRefs: components["schemas"]["SourceReferenceView"][];
            /** Updatedat */
            updatedAt: string;
            /**
             * Verificationsummary
             * @enum {string}
             */
            verificationSummary: "VERIFIED" | "UNVERIFIED" | "MISSING";
        };
        /** WordFormSummary */
        WordFormSummary: {
            /** Id */
            id: string;
            /** Lemma */
            lemma: string;
            /** Meaningvimatch */
            meaningViMatch: string;
            /** Notedates */
            noteDates: string[];
            /** Partofspeech */
            partOfSpeech: string;
            /** Revision */
            revision: number;
            /** Updatedat */
            updatedAt: string;
            /**
             * Verificationsummary
             * @enum {string}
             */
            verificationSummary: "VERIFIED" | "UNVERIFIED" | "MISSING";
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_consent_api_v1_ai_consent_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AiConsentView"];
                };
            };
            /** @description Error Response */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Error Response */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Error Response */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Error Response */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Error Response */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Error Response */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Error Response */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Error Response */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConsentErrorResponse"];
                };
            };
        };
    };
    grant_consent_api_v1_ai_consent_put: {
        parameters: {
            query?: never;
            header: {
                "If-Match": string;
                "Idempotency-Key": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GrantAiConsent"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AiConsentMutationResult"];
                };
            };
            /** @description Error Response */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Error Response */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Error Response */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Error Response */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConsentErrorResponse"];
                };
            };
            /** @description Error Response */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Error Response */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Error Response */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConsentErrorResponse"];
                };
            };
        };
    };
    revoke_consent_api_v1_ai_consent_delete: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AiConsentMutationResult"];
                };
            };
            /** @description Error Response */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Error Response */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Error Response */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Error Response */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConsentErrorResponse"];
                };
            };
            /** @description Error Response */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Error Response */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Error Response */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConsentErrorResponse"];
                };
            };
        };
    };
    get_health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthSummary"];
                };
            };
            /** @description Error Response */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Error Response */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Error Response */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Error Response */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Error Response */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Error Response */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Error Response */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Error Response */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Error Response */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_operation_api_v1_operations__operation_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                operationId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Operation"];
                };
            };
            /** @description Error Response */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Error Response */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Error Response */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Error Response */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Error Response */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Error Response */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Error Response */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Error Response */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Error Response */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_sources_api_v1_sources_get: {
        parameters: {
            query?: {
                status?: ("VALID" | "INVALID" | "MISSING") | null;
                noteDate?: string | null;
                pageSize?: number;
                cursor?: string | null;
                sortBy?: "updatedAt" | "noteDate" | "status" | "revision";
                sortOrder?: "asc" | "desc" | "ASC" | "DESC";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceFilePage"];
                };
            };
            /** @description Error Response */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Error Response */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Error Response */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Error Response */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Error Response */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Error Response */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Error Response */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Error Response */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Error Response */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    create_sync_run_api_v1_sync_runs_post: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateSyncRunRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SyncRunView"];
                };
            };
            /** @description Error Response */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Error Response */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Error Response */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Error Response */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SyncRunConflictErrorResponse"];
                };
            };
            /** @description Error Response */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Error Response */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Error Response */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Error Response */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_sync_run_api_v1_sync_runs__syncRunId__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                syncRunId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SyncRunView"];
                };
            };
            /** @description Error Response */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Error Response */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Error Response */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Error Response */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Error Response */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Error Response */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Error Response */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Error Response */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Error Response */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    list_word_forms_api_v1_word_forms_get: {
        parameters: {
            query?: {
                meaningVi?: string | null;
                lemma?: string | null;
                partOfSpeech?: ("NOUN" | "VERB" | "ADJECTIVE" | "ADVERB" | "PRONOUN" | "PREPOSITION" | "CONJUNCTION" | "INTERJECTION" | "DETERMINER") | null;
                verificationStatus?: ("VERIFIED" | "UNVERIFIED" | "MISSING") | null;
                noteDate?: string | null;
                sourceStatus?: ("VALID" | "INVALID" | "MISSING") | null;
                pageSize?: number;
                sortBy?: "relevance" | "updatedAt" | "lemma";
                sortOrder?: "ASC" | "DESC" | "asc" | "desc";
                cursor?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WordFormCollection"];
                };
            };
            /** @description Error Response */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Error Response */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Error Response */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Error Response */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Error Response */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Error Response */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Error Response */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Error Response */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Error Response */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_word_form_api_v1_word_forms__wordFormId__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                wordFormId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WordFormDetail"];
                };
            };
            /** @description Error Response */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Error Response */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Error Response */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Error Response */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Error Response */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Error Response */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Error Response */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Error Response */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Error Response */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    exchange_bootstrap_bootstrap_exchange_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BootstrapExchange"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error Response */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Error Response */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Error Response */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Error Response */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Error Response */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Error Response */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Error Response */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Error Response */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Error Response */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
